language: node_js
node_js:
  - "0.12"
branches:
  only:
    - master
before_install:
  - npm install -g gulp gulp-cli
  - git config --global user.email "morriswchris@gmail.com"
  - git config --global user.name "Chris Morris"
script: gulp
